---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  #log_level: info

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    driver:
      vm_hostname: jupyterhub
      customize:
        natdnshostresolver1: "on"
      network:
        - ["forwarded_port", {guest: 8000, host: 8000, auto_correct: true}]  # jupyterhub http
        - ["forwarded_port", {guest: 8443, host: 8443, auto_correct: true}]  # jupyterhub https
        - ["forwarded_port", {guest: 8081, host: 8081, auto_correct: true}]  # jupyterhub rest api
    run_list:
      - recipe[jupyterhub::python]
      - recipe[jupyterhub::nodejs]
      - recipe[jupyterhub::anaconda]
      - recipe[jupyterhub::jupyterhub]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      dev_mode: true
